#pragma once

#define VERTEX_ATTRIBUTE_POSITION_NAME "a_position"
#define VERTEX_ATTRIBUTE_NORMAL_NAME "a_normal"
#define VERTEX_ATTRIBUTE_COLOR_NAME "a_color"
#define VERTEX_ATTRIBUTE_COLOR_TOP_LEFT_NAME "a_colorTopLeft"
#define VERTEX_ATTRIBUTE_COLOR_TOP_RIGHT_NAME "a_colorTopRight"
#define VERTEX_ATTRIBUTE_COLOR_BOTTOM_LEFT_NAME "a_colorBottomLeft"
#define VERTEX_ATTRIBUTE_COLOR_BOTTOM_RIGHT_NAME "a_colorBottomRight"
#define VERTEX_ATTRIBUTE_TEXCOORD_PREFIX_NAME "a_texCoord"
#define VERTEX_ATTRIBUTE_BONE_INDEX_NAME "a_boneIndex"

#define VERTEX_ATTRIBUTE_IS_QUAD "a_isQuad"
#define VERTEX_ATTRIBUTE_QUAD_VERT1 "a_quadVert1"
#define VERTEX_ATTRIBUTE_QUAD_VERT2 "a_quadVert2"
#define VERTEX_ATTRIBUTE_QUAD_VERT3 "a_quadVert3"
#define VERTEX_ATTRIBUTE_QUAD_VERT4 "a_quadVert4"
#define VERTEX_ATTRIBUTE_QUAD_UV12 "a_quadUv12"
#define VERTEX_ATTRIBUTE_QUAD_UV34 "a_quadUv34"
