#pragma once

#define VERTEX_ATTRIBUTE_POSITION_NAME "a_position"
#define VERTEX_ATTRIBUTE_NORMAL_NAME "a_normal"
#define VERTEX_ATTRIBUTE_COLOR_NAME "a_color"
#define VERTEX_ATTRIBUTE_COLOR_TOP_LEFT_NAME "a_colorTopLeft"
#define VERTEX_ATTRIBUTE_COLOR_TOP_RIGHT_NAME "a_colorTopRight"
#define VERTEX_ATTRIBUTE_COLOR_BOTTOM_LEFT_NAME "a_colorBottomLeft"
#define VERTEX_ATTRIBUTE_COLOR_BOTTOM_RIGHT_NAME "a_colorBottomRight"
#define VERTEX_ATTRIBUTE_TEXCOORD_PREFIX_NAME "a_texCoord"
#define VERTEX_ATTRIBUTE_TEXINDEX_NAME "a_texIndex"
#define VERTEX_ATTRIBUTE_BONE_INDEX_NAME "a_boneIndex"
