#define BINDING_UNIFORM_TRANSFORM 0
#define BINDING_UNIFORM_CAMERA 1
#define BINDING_UNIFORM_CSM 2
#define BINDING_BUFFER_LIGHTS 3
#define BINDING_BUFFER_DYN_LIGHTS 4
#define BINDING_UNIFORM_CSMVSM 4
#define BINDING_BUFFER_BONE_TRANSFORM 10
#define BINDING_BUFFER_NEXT_BONE_TRANSFORM 11
