if( TARGET glm )
    return()
endif()

if( VCPKG_TOOLCHAIN )
    find_package( glm CONFIG REQUIRED )
else()
    find_package( glm REQUIRED )
    if( NOT TARGET glm )
        add_library( glm INTERFACE IMPORTED )
        target_include_directories( glm SYSTEM BEFORE INTERFACE ${GLM_INCLUDE_DIR} )
    endif()
endif()
target_compile_definitions( glm INTERFACE -DGLM_ENABLE_EXPERIMENTAL -DGLM_FORCE_RADIANS -DGLM_FORCE_CXX${CMAKE_CXX_STANDARD} )
